name: quiz_app_1
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  # cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  path_provider: ^2.1.5
  passwordfield: ^0.2.0 # for password field
  flutter_launcher_icons: ^0.14.3 # for app icon and splash screen
  flutter_svg: ^2.0.17  # for svg images
  percent_indicator: ^4.2.4
  # firebase plugins
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2

  google_sign_in: ^6.2.2

  # for phone sign in
  flutter_localization: ^0.3.1
  intl_phone_field: ^3.1.0
  pinput: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/overleaf.png"
  min_sdk_android: 21


flutter:
  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: quicksand
      fonts:
        - asset: assets/fonts/quicksand/Quicksand-SemiBold.ttf
        - asset: assets/fonts/quicksand/Quicksand-Regular.ttf
        - asset: assets/fonts/quicksand/Quicksand-Medium.ttf
        - asset: assets/fonts/quicksand/Quicksand-Light.ttf
        - asset: assets/fonts/quicksand/Quicksand-Bold.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
